[Feat/#331] 404 페이지 추가
TEAM-BEAT/BEAT-Client pull request #332
Opened 2024-08-09 01:59 UTC by pepperdad

## 📌 관련 이슈번호

- Closes #331 

## 🎟️ PR 유형

어떤 변경 사항이 있나요?

- [x] 새 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 리팩토링

## ✅ Key Changes

> 이번 PR에서 작업한 내용을 간략히 설명해주세요

1. 404 페이지 추가

## 📸 스크린샷

<img width="365" alt="image" src="https://github.com/user-attachments/assets/251b064f-7c3c-4c98-a93d-dbf7e68b6835">

2024-08-09 09:01 UTC, sinji2102 approved these changes
분명 이슈 판 지 얼마 안 됐던 것 같았는데........... 역시 레개도.............. 너무 좋아욥

2024-08-09 09:01 UTC, sinji2102 commented on src/pages/notFound/NotFound.tsx
> +      <S.SubText>너 때문에 비트가 다 깨져버렸으니 책임져.!</S.SubText>
p3) 여기 마침표 하나 잘못 들어간 것 같은데 피그마두 저렇네용 키키 제가 피그마에 물어봐두께욥...

2024-08-09 15:49 UTC, imddoy requested changes
<img width="385" alt="image" src="https://github.com/user-attachments/assets/6d5f1761-0241-47f1-aebc-16abee6e35fc">
gig 뒤에 이상한 링크 붙는거랑
<img width="368" alt="image" src="https://github.com/user-attachments/assets/b4b30477-1782-455b-8cc8-e75a36426b47">
공연 데이터 없는 경우에도 404처리 해야할 것 같습니다!!

2024-08-10 06:31 UTC, pepperdad commented
@imddoy 감사합니다! 반영하겠습니다!

2024-08-10 06:44 UTC, sinji2102 commented on src/pages/notFound/NotFound.tsx
> +      <S.SubText>너 때문에 비트가 다 깨져버렸으니 책임져.!</S.SubText>
p3) 느낌표 하나가,,, 맞다구 함미다,,,
![image](https://github.com/user-attachments/assets/066e1769-0daf-46ec-953c-03e6a0215249)

2024-08-11 09:34 UTC, pepperdad commented
@imddoy 반영했습니다 :)

2024-08-12 09:44 UTC, ocahs9 approved these changes
LGTM ! 지적할만한 부분들은 다른 분들이 잘 지적해주셨고, 반영도 다 하셨네요!
이제 병합해도 될 듯 합니당 고생하셨습니다 ~~

2024-08-12 09:45 UTC, imddoy approved these changes

2024-08-12 16:34 UTC, merged