[Feat/#439] 예매 취소 구현
TEAM-BEAT/BEAT-Client pull request #449
Opened 2024-11-23 21:47 UTC by imddoy

## 📌 관련 이슈번호

- Closes #439 

## 🎟️ PR 유형

어떤 변경 사항이 있나요?

- [x] 새 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 리팩토링

## ✅ Key Changes

> 이번 PR에서 작업한 내용을 간략히 설명해주세요

1. 예매 취소 구현
2. 예매 조회 staleTime 30분으로 변경
3. 예매 조회 화면 깜빡임 해결

## 📢 To Reviewers

- 스키마가 아직 없어서 임의로 작성해서 에러납니다!!!

## 📸 스크린샷

## 🔗 참고 자료

2024-12-04 08:47 UTC, pepperdad requested changes
고생하셨습니다! 
리뷰 남긴 거 확인해주세요 ~ 

그리고 yarn build 실행 시 나오는 에러들만 수정해주세요!

2024-12-04 08:47 UTC, pepperdad commented on src/routes/Router.tsx
> +      { path: "cancel", element: <Cancel /> },
p1:
지금 경로가 `/cancel` 인데, 
Lookup 페이지에서 취소 요청을 하면 보이니까 
`/lookup/cancel` 이 더 적절해 보여요!

2024-12-04 08:47 UTC, pepperdad commented on src/routes/Router.tsx
> +      { path: "cancel", element: <Cancel /> },
그리고 lookup 라우트 안에 넣으면 좋을 것 같아용

2024-12-04 08:47 UTC, pepperdad commented on src/pages/nonMbLookup/NonMbLookup.tsx
> +      });
p2:
지금에서야 리뷰를 남기지만,,, 
이렇게 상수 부분을 다음 스프린트에서 분리해서 사용하면 좋을 것 같아용
```typescript
const ERROR_MESSAGES = {
  DEFAULT: "일치하는 정보가 없습니다. \n 확인 후 다시 조회해 주세요",
  NETWORK: "네트워크 오류가 발생했습니다.",
  SERVER: "서버 오류가 발생했습니다."
} as const;
```
이렇게 const 파일로 분리하는 작업을 다음 스프린트에서 해봅시당!

2024-12-04 08:47 UTC, pepperdad commented on src/pages/nonMbLookup/NonMbLookup.tsx
> +  });
p2: 
요기 state 의 변수 네이밍을 조금 바꾸면 좋을 거 같아요!

```suggestion
  const [formData, setFormData] = useState({
    name: "",
    birth: "",
    phone: "",
    password: "",
  });
```
이렇게 바꾸면 아래에서 조금 더 간략하게 사용할 수 있어요!

2024-12-04 08:47 UTC, pepperdad commented on src/pages/nonMbLookup/NonMbLookup.tsx
> +          },
p2: 여기서요! 

```suggestion
  const handleBtnClick = async () => {
    try {
      setIsFetching(true);

      const bookingData = await fetchBookingList(formData);

      if (bookingData) {
        navigate("/lookup", {
          state: formData,
```

이렇게 변수 네이밍만 조금 수정해줘도 더 쉽게 사용할 수 있어요!

2024-12-04 08:47 UTC, pepperdad commented on src/pages/lookup/Lookup.tsx
>        });
p2: 
아까 nonMb에서 전달한 state를 가지고
요기서도 state 객체를 바로 넣으면 될 것 같아요!

2024-12-04 08:47 UTC, pepperdad commented on src/pages/cancel/Cancel.tsx
> +  }, [state, openAlert, navigate]);
p1: 
이렇게 지금 작성했어도 `useEffect`보다 위의 

`useCancelBooking`,
`const performanceDateArray = state.bookingDetails.performanceDate.split("-");`
`const performanceDataDate = performanceDateArray[2].split("T");`

이 로직들이 먼저 실행되고 있어서, url을 통해서 바로 접근해보시면 useEffect 내부의 로직이 실행되지 않고 있어요! 
**리액트의 라이프사이클**을 공부해보면 좋을 것 같아요!

이 부분은 https://i-ten.tistory.com/308 
이 아티클의 2. useEffect의 실행순서를 참고하면 좋을 것 같아요! 왜 안되는지 생각해보고 수정해보길! 

또한, `okCallback: () => navigate(-1)` 을 url을 통해서 접근한 사용들은 이전 페이지로 비트를 빠져나갈 수도 있어요! 
이 부분은 lookup으로 가게 하는 게 좋을 거 같아요!

2024-12-04 08:47 UTC, pepperdad commented on src/pages/cancel/Cancel.tsx
> +  }, [state, openAlert, navigate]);
p1: 
그리고 url을 통해서 바로 들어올 때, 로그를 찍어보시면 지금 무한 렌더링이 되고있어요!
```suggestion
  }, []);
```

요기의 dependency를 없애면 무한 렌더링이 발생하지 않는데! 이 부분도 왜 그런건지 공부하고 저한테 설명해주세요 ~

2024-12-04 08:47 UTC, pepperdad commented on src/hooks/useCancelBooking.tsx
> +          okText: "확인",
p4: 요기 부분도 추후에 const 로 빼면 좋겠쬬잉

2024-12-05 13:51 UTC, sinji2102 approved these changes
제가 봤을 때 엄청 큰 문제는 없는 것 같아서 어푸하겠습니다!! 피그마랑 다른 부분만 확인해 주세용 🍀

2024-12-05 13:51 UTC, sinji2102 commented on src/pages/cancel/Cancel.tsx
> +              filter={(value: string) => value.replace(/[^0-9]/g, "")} // 숫자만 허용
p5) 헉 숫자만 받는 numericFilter가 있는 거로 알고 있는데 이렇게 사용하신 이유가 따로 있나요??

계좌번호를 받는 건 동일한데, 등록에는

```
filter={numericFilter}
placeholder="입금 받으실 계좌번호를 (-)제외 숫자만 입력해주세요."
inputMode="numeric"
```

로 되어있어서 둘의 차이가 궁금합니다!!

2024-12-05 13:51 UTC, sinji2102 commented on src/pages/cancel/Cancel.tsx
> +          </table>
p3) 디자인에서 받은 내용과 비교했을 때 구현된 부분이 관람일과 회차가 살짝 들여쓰기 된 것 처럼 보이는 것 같아요!

피그마
![image](https://github.com/user-attachments/assets/a319dbea-827f-4e3c-8e2a-3331c1e635de)


구현 화면
![image](https://github.com/user-attachments/assets/bfb6efb2-33cf-41bc-b8ae-0bd1969fa1b2)

2024-12-05 13:51 UTC, sinji2102 commented on src/pages/cancel/utils/index.ts
> +};
p5) 이 부분 아래처럼 작성해두 되는데 위처럼 한 이유가..... 있으실까 해서 차이점을 검색해 봤는데 선호도의 차이인 것 같아요!!

```javasciprt
import React, { ChangeEvent, Dispatch, SetStateAction } from "react";

export const handleChange = (
  e: ChangeEvent<HTMLInputElement>,
  setState: Dispatch<SetStateAction<string>>
) => {
  setState(e.target.value);
};

export const handleBankClick = (
  value: string,
  setState: Dispatch<SetStateAction<string>>,
  setbankName: Dispatch<SetStateAction<string>>,
  setOpen: Dispatch<SetStateAction<boolean>>
) => {
  setbankName(value);
  setState(value);
  setOpen(false);
};
```

저는 개인적으로 미리 import 하고 쓰는 게 간결해서 좋아하는데 가독성 측면에서는 타입이 React에서 살짝 봐도 알 수 있으니 React.으로 사용하는 게 좋은 것 같기도 하고... 다음에 컨벤션으로 정하면 좋을 것 같아욥

2024-12-05 13:51 UTC, sinji2102 commented on src/pages/nonMbLookup/components/InputWrapper.tsx
p5) 제 거지같던 코드.... 정리해 주셔서 감사합니다.....

2024-12-05 17:25 UTC, imddoy commented on src/pages/cancel/Cancel.tsx
> +              filter={(value: string) => value.replace(/[^0-9]/g, "")} // 숫자만 허용
저거 누가 해둔거 복붙해왔어용 필터로 고칠게영

2024-12-05 17:25 UTC, imddoy commented on src/pages/cancel/Cancel.tsx
> +          </table>
오오 매의 눈 확인해서 고치겠습니당

2024-12-05 17:26 UTC, imddoy commented on src/pages/cancel/utils/index.ts
> +};
우움 import할게용

2024-12-05 17:26 UTC, imddoy commented on src/pages/nonMbLookup/components/InputWrapper.tsx
안 거지 같아용

2024-12-05 18:05 UTC, imddoy commented on src/pages/cancel/Cancel.tsx
> +  }, [state, openAlert, navigate]);
아티클까지 첨부해주셔서 감사합니다!! 이슈 확인해서 해결했습니다!! 로그인한 user가 아니면 lookup으로 가는것이 의미가 없을 것 같아서 localstrage에서 user 여부 판단해서 없으면 main 있으면 lookup으로 이동하도록 반영했습니다!!

2024-12-05 18:18 UTC, sinji2102 commented on src/pages/cancel/utils/index.ts
> +};
헉 import 하자는 거 아니고 컨벤션 정하자는 거엿는ㄷ데!!!!!!!!!!!!! 상관업서요 지금은

2024-12-05 18:28 UTC, imddoy commented on src/pages/cancel/Cancel.tsx
> +  }, [state, openAlert, navigate]);
확인해본 결과 `openAlert`가 계속 새롭게 생성되고 있었습니다!
 `openAlert` 코드를 찾아봤는데
```ts
  const openAlert = (alertProps: Omit<AlertProps, "isOpen">) => {
    setAlert({
      isOpen: true,
      ...alertProps,
    });
  };
```
이렇게 `openModal` 훅 안에 정의되어 있어서 
`const { openAlert } = useModal();` 이렇게 사용하고 있었습니다!

따라서 컴포넌트가 렌더링될 때마다 `openAlert`를 새롭게 생성해서 가져오고 있어서 의존성이 계속 바뀌게 되면서 무한 렌더링 감옥에 갇히게 된거더라구요!!

```ts
const openAlert = useCallback(
    (alertProps: Omit<AlertProps, "isOpen">) => {
      setAlert({
        isOpen: true,
        ...alertProps,
      });
    },
    [setAlert]
  );
```
이렇게 `useCallback`을 감싸서 실행해보니까 의존성에 넣어도 새롭게 생성되고 있지 않아서 변경된다고 판단하지 않아서 렌더링이 반복되지 않는 것을 확인했습니다!

그런데 공용으로 잘 쓰고 있는 훅을 `useCallback`으로 감싸는 것도 헤비하다고 생각했고,
새롭게 생성되지 않도록만 코드를 작성한다면 `useCallback`을 사용하지 않아도 문제가 되지 않기 때문에 제 `useEffect`의 의존성을 수정하는 것이 맞다고 생각했습니다!

의존성을 넣을 때 가끔씩 Warning으로 React는 안에서 사용하는 값들을 의존성으로 넣는 것을 권장한다고 뜨길래,
최근에 의존성에 안에 있는 애들을 넣어줘야겠다고 마음먹었는데 좋지 않은 판단이었던 것 같네요!!
컴포넌트 내에서 해당 값들이 변경될 일이 없다면 굳이 넣지 않는 것이 맞는 것 같습니다!
제가 여기에서 `state`, `openAlert`, `navigate` 3개가 사용되고 있기 때문에 의존성에 넣어줬었는데 잘못된 생각이었네요!
`navigate`는 React Router에서 제공하는 함수라서 참조가 변경되지 않기 때문에 의존성으로 굳이 넣어주지 않아도 된다구 하네용 ㅎㅎ
그리고 현재 `state`는 `useLocation`에서 받아오는 `state`이기 때문에 이 값도 새로 페이지를 접속하지 않는한 변경되지 않기 때문에 의존성을 아예 비워두는 것이 올바른 작성법이겠네요!!
반영 완료했습니다!!

2024-12-05 20:25 UTC, imddoy commented on src/pages/lookup/Lookup.tsx
>        });
친절하게 알려주셔서 state 반영완료했습니당

2024-12-05 20:25 UTC, imddoy commented on src/pages/nonMbLookup/NonMbLookup.tsx
> +      });
ㅎㅎ 다음스프린트 때 할게여.....

2024-12-09 05:41 UTC, merged