[Feat/#453] 예매자 관리 페이지 기능 구현
TEAM-BEAT/BEAT-Client pull request #454
Opened 2024-12-02 20:19 UTC by sinji2102

## 📌 관련 이슈번호

- Closes #453

## 🎟️ PR 유형

어떤 변경 사항이 있나요?

- [x] 새 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 리팩토링

## ✅ Key Changes

- [x] 예매자 조회 GET API 연결
- [x] 예매자 조회 필터링 기능 추가
- [x] 예매자 조회 검색 기능 추가
- [x] 입금 처리 API 연결
- [x] 환불 처리 API 연결
- [x] 예매자 삭제 API 연결
- [x] CSV 다시 연결

## 📢 To Reviewers

- TicketHolderList에 handler가 너무 많아서 뭔가 분리하고 싶었는데... 막상 분리하려니까 애매하고... 해서 일단 한 파일에 들어있어요 ㅠㅠ
- ManageCard 컴포넌트는 합성 컴포넌트를 의도하긴 했는데... 저게 맞는지는 잘 모르겠습니다 ㅠㅠ
- 원래 react-csv가 CSVLink 컴포넌트 안에 버튼 컴포넌트를 넣고 그걸 누르면 CSV가 다운로드 되는 형식으로 알고 있는데, 현재 Navigation 공통 컴포넌트 우측 상단에 컴포넌트를 넣기가 애매해서 useRef로 처리했습니다!
- 검색 처리 때문에 useDebounce 커스텀 hook 만들었는데, 준혁 오빠 주소 검색할 때도 debounce를 사용하는 것 같아서 merge 이후에 공통 hook으로 사용할 수 있게 변경하면 좋을 것 같아요!

## 📸 스크린샷

2024-12-05 03:57 UTC, pepperdad requested changes
투두해주세용

2024-12-05 03:57 UTC, pepperdad commented on src/hooks/useDebounce.ts
p4: 👍

지금은 값을 debounce를 하는데,
[함수 호출 debounce](https://github.com/toss/slash/blob/main/packages/react/react/src/hooks/useDebounce.ts) 할 수도 있어요!
한 번 보면 좋을 것 같아요 ㅎ.ㅎ

2024-12-05 03:57 UTC, pepperdad commented on src/pages/ticketholderlist/TicketHolderList.tsx
> +      // TODO : rightOnClick CSV 다운로드로 변경
p1: TODO 해주세용

2024-12-06 09:29 UTC, imddoy reviewed
우리 신지는 정말 열심히 했구나...ㄷㄷㄷ 최고당!!!! 근데 todo는 언제해주시낭요

2024-12-06 09:29 UTC, imddoy commented on src/pages/ticketholderlist/components/narrowDropDown/NarrowDropDown.styled.ts
p1) 헝헝 컴포넌트도 지워주세용

2024-12-06 09:29 UTC, imddoy commented on src/pages/ticketholderlist/TicketHolderList.tsx
p5) 여기 코드리뷰 안되는거 실화야요??????
에반데... 어떻게 코리남겨요...??

1. 컴포넌트 밖으로 뺄수 있는 상수들은 분리해주는게 좋을 것 같아요!
2. 업데이트를 하고 `reload`를 직접하고 있는데, 리액트 쿼리를 활용하지 못한것 같습니다! 그냥 무효화시켜주면 되지 않나용??
```tsx
    setTimeout(() => {
      window.location.reload();
    }, 1000);
```

2024-12-09 13:36 UTC, pepperdad approved these changes

2024-12-09 14:13 UTC, merged