[Feat/#35] Bottm Sheet 공통 컴포넌트 추가
TEAM-BEAT/BEAT-Client pull request #46
Opened 2024-07-06 19:49 UTC by sinji2102

## 📌 관련 이슈번호

- Closes #35 

## 🎟️ PR 유형

어떤 변경 사항이 있나요?

- [x] 새 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 리팩토링

## ✅ Key Changes

 - [x] View 바텀 시트 생성
 - [x]  Action 바텀 시트 생성
 - [ ] check 바텀 시트 생성

- back는 공통 컴포넌트가 아니라고 판단하여 작업하지 않았습니다!
- 일단 PR 먼저 올려야 할 것 같아서... 그리고 check가 쓰이는 곳이 별로 없길래 일단 작업하지 않고 PR 올립니다....

## 📢 To Reviewers
먼저 사과의 말씀 전합니다. . .  바텀시트가 뭔가 생긴 게 자꾸만 재사용 될 것 같은데 다음에 재사용될 때는 저 형식이 아닌 것 같아 잘게 컴포넌트를 쪼개다 보니까 요상한 코드가 되었어요... 엉엉... 아기개발자가 컴포넌트 분리 욕심을 내면 어떻게 되는지를 보고 계십니다...

### 전체적인 폴더 구조
📦components
 ┣ 📂commons
 ┃ ┣ 📂bottomSheet
 ┃ ┃ ┣ 📂actionsBottomSheet
 ┃ ┃ ┃ ┣ 📂phoneNumber
 ┃ ┃ ┃ ┃ ┣ 📜PhoneNumber.tsx
 ┃ ┃ ┃ ┃ ┗ 📜PhoneNumberStyle.tsx
 ┃ ┃ ┃ ┣ 📜ActionBottomSheet.tsx
 ┃ ┃ ┃ ┗ 📜ActionBottomSheetStyle.tsx
 ┃ ┃ ┣ 📂viewBottomSheet
 ┃ ┃ ┃ ┣ 📜ViewBottomSheet.tsx
 ┃ ┃ ┃ ┗ 📜ViewBottomSheetStyle.tsx
 ┃ ┃ ┣ 📜BottomSheet.tsx
 ┃ ┃ ┗ 📜BottomSheetStyle.tsx
 ┃ ┗ 📂contextBox
 ┃ ┃ ┣ 📜Context.tsx
 ┃ ┃ ┣ 📜ContextBox.tsx
 ┃ ┃ ┣ 📜ContextBoxStyle.tsx
 ┃ ┃ ┗ 📜ContextStyle.tsx
 ┗ 📂ex-stories
 ┃ ┣ 📜button.css
 ┃ ┣ 📜Button.stories.ts
 ┃ ┗ 📜Button.tsx

### View Bottom Sheet
- 패드로 수정

### Acton Bottom Sheet
- 패드로 수정

## 📸 스크린샷

### View Bottom Sheet
![image](https://github.com/TEAM-BEAT/BEAT-Client/assets/66528589/a8a5ef1c-a17e-4ff1-b193-5dc487ea5730)

### Action Bottom Sheet
![image](https://github.com/TEAM-BEAT/BEAT-Client/assets/66528589/edfad883-48f6-4146-9cff-3d9e1f41817d)

2024-07-07 06:38 UTC, pepperdad requested changes
최고신지 고생해써 ~!!~!
확장성 고려해서 잘 했넹 ~~ PR에 설명도 잘 되어있어서 좋았어!!!
리뷰 한 번 확인해줘!
우리 interface 컨벤션이 PropsTypes가 아니라 PropTypes 여서 이 부분 전체적으로 수정해서 다시 올려줘✌️

2024-07-07 06:38 UTC, pepperdad commented on src/components/commons/bottomSheet/actionsBottomSheet/ActionBottomSheet.tsx
> +import PhoneNumber from "./phoneNumber/PhoneNumber";
p4) 필요없는 import 문은 삭제해도 좋을 것 같아요!

2024-07-07 06:38 UTC, pepperdad commented on src/components/commons/bottomSheet/viewBottomSheet/ViewBottomSheetStyle.tsx
> +import { boxTitleStyle, boxDividerStyle } from "../../../../types/contextBoxPropsTypes";
p4) 타입 부분 지금 alias를 통해서 안되어있는데, 머지하기 전이나 머지한 후, @typings 폴더로 바꿔서 하면 alias 적용될 거예요! 
나중에 확인 부탁드립니다!

2024-07-07 06:38 UTC, pepperdad commented on src/components/commons/contextBox/ContextBox.tsx
> +      </S.ContextBoxLayout>
p4) `S.ContextBoxLayout` 컴포넌트가 width, height등 여러가지 스타일링 속성을 props로 받을 수 있는데, 지금 전달하는 거에서는 alignItems, padding, gap 밖에 없어요! 
이 부분 확장을 위해서라면 아래와 같이 구조분해 할당으로 나머지 props를 전달하는 게 어떨까요!?
```suggestion
      <S.ContextBoxLayout alignItems={customAlignItems} padding={customPadding} gap="1.2rem" {...rest}>
        {children}
      </S.ContextBoxLayout>
```

2024-07-07 06:38 UTC, pepperdad commented on src/components/commons/bottomSheet/viewBottomSheet/ViewBottomSheet.tsx
> +        <ContextBox customPadding="1.6rem 1.6rem">
p4) 그럼 여기서도 전달해야겠죠!?
```suggestion
        <ContextBox customPadding="1.6rem 1.6rem" {...rest}>
```

2024-07-07 06:38 UTC, pepperdad commented on src/components/commons/bottomSheet/actionsBottomSheet/phoneNumber/PhoneNumber.tsx
> +    navigator.clipboard.writeText(text);
p5) 복사 굿!!! 
노트북에서는 잘 동작하는데, 모바일에서도 잘 동작하는지 확인해야봐야겠네욥

2024-07-07 06:38 UTC, pepperdad commented on src/components/commons/bottomSheet/BottomSheetStyle.tsx
p3) 저희 컨벤션이 ComponentStyle.tsx 가 아니라, Component.styled.tsx 입니다! 
전체적으로 다 그렇게 작성하셔서 요 부분 수정 부탁드릴게요!

2024-07-07 06:38 UTC, pepperdad commented on src/components/commons/bottomSheet/BottomSheet.tsx
p5) 추가로 아래와 같이 index.ts 파일에서 export 해주면 사용하는 곳에서 import 문을 하나로 합칠 수 있어요! 
```typescript 
// index.ts
export { default as ActionBottomSheet } from "./actionsBottomSheet/ActionBottomSheet";
export { default as PhoneNumber } from "./actionsBottomSheet/phoneNumber/PhoneNumber";
export { default as ViewBottomSheet } from "./viewBottomSheet/ViewBottomSheet";
```
아래 사진처럼요! 이렇게 사용하면 import 문도 조금 줄어들 수 있어요! 
<img width="1451" alt="image" src="https://github.com/TEAM-BEAT/BEAT-Client/assets/58854041/608f8916-7c17-4f96-a12e-943dbf76eceb">

이 부분은 제가 svg 파일 바꾸는 것처럼 스크립트로 추후에 바꾸도록 하겠습니다...!

2024-07-07 08:17 UTC, imddoy approved these changes
우리 갓기 최고신지..... 로직짜느라 고생하더니 대박 멋진 코드를 작성해버렸넹 최고다 헤헤 컨벤션만 지키면 될듯요?ㅎㅎㅎ

2024-07-07 08:17 UTC, imddoy commented on src/components/commons/bottomSheet/BottomSheetStyle.tsx
> +`;
p5) 제목 길어지면 ... 으로 표시되도록 해야 할 것 같은데, 디자이너랑 상의해보셔야 할 것 같습니다.
<img width="652" alt="image" src="https://github.com/TEAM-BEAT/BEAT-Client/assets/90364711/971be9f1-46bf-4428-85e8-5289d9bfdfc8">

2024-07-07 08:17 UTC, imddoy commented on src/components/commons/bottomSheet/actionsBottomSheet/phoneNumber/PhoneNumber.tsx
> +  };
p5) 꼼꼼한 주석처리~~ 폼미

2024-07-07 08:17 UTC, imddoy commented on src/components/commons/contextBox/ContextBox.tsx
> +      </S.ContextBoxLayout>
p5) 저도 이 부분 놓쳤던 것 같은데 확인해봐야겠네용 감사합니다

2024-07-07 12:28 UTC, ocahs9 approved these changes
어떻게 이렇게 장기적으로 코드를 생각하면서 구성할 수 있는지..!
재사용성을 고려하느라고 컴포넌트 분리 엄청 해놓았던데 고생 많이 했어요!!
수고 많았어 😊

2024-07-07 12:28 UTC, ocahs9 commented on index.html
> +    <link rel="stylesheet" href="./src/styles/fonts/fonts.css" />
p5) 해결됐으니 굿굿~

2024-07-07 12:28 UTC, ocahs9 commented on src/components/commons/bottomSheet/actionsBottomSheet/ActionBottomSheet.tsx
> +import PhoneNumber from "./phoneNumber/PhoneNumber";
p4) 도영님이 말씀해주신 것처럼 필요없는 import 문은 삭제해주세요! 그런데 아마 eslint 혹은 prettier로 인해서 자동 삭제 되었던 것 같은데 혹시 안되시나요..?

2024-07-07 12:28 UTC, ocahs9 commented on src/components/commons/bottomSheet/actionsBottomSheet/phoneNumber/PhoneNumber.tsx
> +    navigator.clipboard.writeText(text);
p5) 오 요거 어떻게 복사하나 했는데.. navigator.clipboard 라는 방법이 있었군요 !!
좋네요 굿굿 !

2024-07-07 12:28 UTC, ocahs9 commented on src/components/commons/bottomSheet/viewBottomSheet/ViewBottomSheetStyle.tsx
> +    theme.colors[customColor as keyof typeof theme.colors]};
p5) 타입 단언 쓰는 거 처음 보는데 좋네요 !!

2024-07-07 12:28 UTC, ocahs9 commented on src/styles/fonts/fonts.css
> +  font-family: Pretendard;
p5) 고민의 흔적이 보이네요 ㅋㅋㅋ 그래도 잘 적용되서 다행입니다 !!

2024-07-07 18:50 UTC, sinji2102 commented
**버튼 관련해서 코드 수정해서 PR도 수정했으니 다들 잘 읽어주기!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**

2024-07-08 14:13 UTC, pepperdad requested changes
신지야 확인했어! 
children 분리도 너무 잘했고, ButtonLayout은 신지가 OuterLayout으로 만든거지? 이 부분도 좋아! 
근데 이 BottomSheet 컴포넌트는 화면의 젤 하단에 붙어있어야하잖아!
그래서 컴포넌트가 동작할 때, 화면의 뷰포트에서 아래 쪽에서 나와야할 것 같아! 
이 부분은 position을 absolute로 하든지 혹은 다른 방법을 사용해서 하는 걸 고민해봐! 이 부분 수정하면 머지해도 될 것 같아 ~!

2024-07-08 15:53 UTC, pepperdad reviewed
https://github.com/TEAM-BEAT/BEAT-Client/pull/45 
이 PR의 styled-component 에서 `$` 쓰는 코멘트 달아놧는데 확인해보시면 좋을 것 같아요!

2024-07-09 06:28 UTC, pepperdad approved these changes
리뷰 남긴 부분만 수정하고 머지해줘,,,

2024-07-09 06:28 UTC, pepperdad commented on src/components/commons/bottomSheet/actionsBottomSheet/ActionBottomSheet.styled.ts
> +  left: 0;
p3) 
<img width="1624" alt="image" src="https://github.com/TEAM-BEAT/BEAT-Client/assets/58854041/12024ac8-d123-407c-a115-ce4c11d8e1ac">

신지야 모바일 뷰에서는 지금 하단에 잘 나오는데, 이게 pc에서보면 <img width="1624" alt="image" src="https://github.com/TEAM-BEAT/BEAT-Client/assets/58854041/472361f3-af07-4425-9e66-bb0bef222148">
이렇게 화면의 왼쪽 하단에 붙어서 나와 ㅠㅠ 
이 부분은 아래처럼 코드 수정하면 중앙 하단에 나올 거야! 물론 지금은 필요 없을 수도 있겠지만, 나중에 pc에서도 BottomSheet 사용한다고 생각하면 아래처럼 수정하는 게 좋을 것 같아! 
```suggestion
  left: auto;
```
ViewBottomSheet도 똑같은 현상이 발생해서 이 부분만 수정하고 머지해도 될 것 같아~!
고생했어!!!

2024-07-09 06:35 UTC, merged